import type { Metadata } from "next";
import { ReactNode } from "react"; // ReactNode 타입 가져오기
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          {/* Sidebar */}
          <nav className="w-64 bg-gray-800 text-white h-screen p-4">
            <ul className="space-y-4">
              <li><a href="/login">로그인</a></li>
              <li><a href="/dashboard">대시보드</a></li>
              <li><a href="/user-management">사용자 관리</a></li>
              <li><a href="/role">권한 및 역할 관리</a></li>
              <li><a href="/activity-logs">활동 로그</a></li>
              <li><a href="/service-settings">서비스 설정</a></li>
              <li><a href="/reports">신고 및 문의 관리</a></li>
              <li><a href="/analytics">통계 및 보고서</a></li>
              <li><a href="/system-monitoring">시스템 모니터링</a></li>
            </ul>
          </nav>
          {/* Main Content */}
          <main className="flex-1 p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
